config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'
  get 'topics/new'
  get 'sessions/new'

  root 'homes#top'
  
  get 'homes/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :topics

  #いいね機能
  get 'likes/index'
  # お気に入りの追加
  post '/likes', to: 'likes#create'
  # お気に入りの削除
  delete "/likes", to: "likes#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #コメントの送信
  post "topics/comments", to: "comments#create"
  #コメントの削除
  delete "/comments", to:"comments#destroy"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user
  belongs_to :topic

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
validates :user_id, presence: true
validates :f_date, presence: true
validates :field, presence: true
validates :description, presence: true
validates :image, presence: true

belongs_to :user

mount_uploader :image, ImageUploader

#いいねテーブルとの関連
has_many :likes
#投稿にいいねしたユーザーのデータを全て取得
has_many :like_users, through: :likes, source: "user"

#コメントテーブルとの関連
has_many :comments


end

app/models/user.rb
class User < ApplicationRecord

  # 各フォームに値が入っているか確認
  validates :name,  presence: { message: "%{value} を入力してください" }
  validates :email, presence: { message: "%{value} を入力してください" }
  validates :password, presence: { message: "%{value} を入力してください" }

  #名前の文字数制限
  validates :name, length: { maximum: 15,message: "は15字以内にしてください" }

  #メールの形式に関する制限
  validates :email, format: { with: /[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/,
    message: "は~ @ ~ . ~の表現にしてください" }


    #パスワードの文字数制限
    validates :password, length: { in: 8..32, too_long: "は３２文字以内にしてください", too_short: "は８文字以上にしてください"}

    validates :password, format: { with: /(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)/,
      message: "%{value}はアルファべット（大小）と半角数字の混合にしてください" }

    #パスワードが一致しているかの確認
    # validates :password, confirmation: true
    validates :password, confirmation: { message: "とpasswordの値が一致していません" }
    # validates :password_confirmation, presence: true

  has_secure_password
  #投稿テーブル
  has_many :topics

  # いいねテーブル
  has_many :likes
  #ユーザーがいいねしたTopicデータを全て取得
  has_many :like_topics, through: :likes, source: 'topic'

  #コメントテーブル
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  # extend ApplicationHelper

  helper_method :current_user, :logged_in?

  def current_user
    # @current_user が偽か未定義ならばUser~を代入
    @current_user ||=User.find_by(id: session[:user_id])

  end

  def logged_in?
    !current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new
    @comment[:body]=comment_params[:body]
    @comment[:user_id]=current_user.id
    @comment[:topic_id]=comment_params[:topic_id]
    topic_id = comment_params[:topic_id]

    if @comment.save
      #投稿詳細画面表示
      redirect_to topic_path(topic_id)
    else
      #投稿詳細画面表示
      redirect_to topic_path(topic_id), danger: "コメント投稿に失敗しました"
    end
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
    redirect_to topics_path, danger: "コメント投稿を削除しました"
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :topic_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
    @like_topics = current_user.like_topics.all.order(created_at: :desc)
  end

  def create
    like = Like.new
    like.user_id = current_user.id
    like.topic_id = params[:topic_id]

    if like.save
      #投稿詳細画面表示
      redirect_to topic_path(like.topic_id), success: 'お気に入りに登録しました'
    else
      redirect_to topics_path, danger: 'お気に入り登録に失敗しました'
    end
  end

  #いいねの削除
  def destroy
    like = Like.find_by(user_id: current_user.id, topic_id: params[:topic_id])
    like.destroy
    #投稿詳細画面表示
    redirect_to topic_path(like.topic_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # フォームから送信されたメアド取得し一致するユーザー検索
    @user = User.find_by(email_params)
    # ユーザーのPWが正しいか確認
    if @user && @user.authenticate(password_params[:password])
      log_in @user
      redirect_to topics_path,success:"ログインに成功しました"
    else
      flash.now[:danger]= "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end

  private
  def log_in(user)
    session[:user_id]=user.id
  end

  # emailのstrong_params
  def email_params
    params.require(:session).permit(:email)
  end

  # passwordのstrong_params
  def password_params
    params.require(:session).permit(:password)
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
   @topics = Topic.all.order(created_at: :desc)
  end

  def show
    @topic = Topic.find_by(id: params[:id])
    #コメント一覧を表示するための設定
    @comments=Comment.all

    #topic/showに反映させたい場合は記述
    @comment=Comment.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path,success: "投稿に成功しました"
    else
      flash.now[:danger]="投稿に失敗しました"
      render :new
    end
  end

 # 削除機能の実装
  def destroy
     @topic =Topic.find(params[:id])
     # @topic =Topic.find(id: params[:id])
     @topic.destroy
     redirect_to topics_path,success: "画像を削除しました"
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :f_date, :field, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end
  def create
    # binding.pry
    # @user=User.new(name: params[:user][:name],email: params[:user][:email])
    @user=User.new(user_params)

    if @user.save
      redirect_to root_path,success: "登録が完了しました"
    else
      flash.now[:danger]="登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #現在ログインしているユーザー
  #def current_user
  #  @current_user || = User.find_by(id: #session[:user_id])
  #end

  #ログイン中か確認
  #def logged_in?
  #  !current_user.nil?
  #end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">You can catch Nerima Salmon!!!</h1>
    <h2 class="text-white">NFA倶楽部はとしまえんフィッシングエリアの釣客向けのサービスです。</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to "新規登録",new_user_path,class: "btn btn-block btn-white"%>
      </div>
      <div class="col-md-3">
        <%= link_to "Log in",login_path,class: "btn btn-block btn-white"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>NFAClub</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    </head>

    <body>
        <% flash.each do |key,value| %>
            <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
        <% end %>
        <div class="container">
        <nav class="navbar navbar-default navbar-expand navbar-fixed-top navbar-transparent" style="background-color: #afeeee;">

        <!-- Collapse button -->
        <button class="navbar-toggler toggler-example visible-xs-inline" type="button" data-toggle="collapse" data-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1" aria-expanded="false" aria-label="Toggle navigation">
          <span class="dark-blue-text"><i class="fas fa-bars fa-1x"></i></span>
        </button>

        <!-- Collapsible content -->
        <!-- 画面幅が所定のサイズ以下になったときに折りたたまれグルーピング -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">
            <!-- top画面 -->
            <%= link_to root_path do %>
            <span><%= image_tag "icons/mylogo.png", class: "navbar-brand hidden-xs" %></span>
            <% end %>

            <ul class="nav navbar-nav mr-auto navbar-right">

                <!-- ログイン済みならば -->
                <% if logged_in? %>
                <!-- マイページに戻るリンク追加 -->
                <li class = "nav-item">
                    <%= link_to topics_path, class: "nav-link" do %><span class="sr-only">(current)</span>
                        <%= image_tag "icons/my_img.png", class: "hidden-xs" %><br>投稿一覧
                    <% end %>
                </li>
                <!-- いいね一覧リンク -->
                <li class = "nav-item">
                    <%= link_to likes_index_path, class: "nav-link" do %>
                        <%= image_tag "icons/heart.png", class: "hidden-xs" %><br>いいね
                <% end %>
                </li>
                <!-- 新規投稿頁リンク -->
                <li class = "nav-item">
                    <%= link_to new_topic_path, class: "nav-link" do %>
                        <%= image_tag "icons/camera.png", class: "hidden-xs" %><br>新規投稿
                    <% end %>
                </li>
                <!-- ログアウト頁へのリンク -->
                <li class = "nav-item">
                    <%= link_to logout_path, class: "nav-link", method: :delete do %>
                        <%= image_tag "icons/logout.png", class: "hidden-xs" %><br>logout
                    <% end %>
                </li>
                <!-- ログインしていなければ -->
                <% else %>
                <!-- 新規登録ページへ -->
                <li class = "nav-item">
                    <%= link_to new_user_path, class: "nav-link" do %>
                        <%= image_tag "icons/register.png", class: "hidden-xs" %><br>新規登録
                    <% end %>
                </li>
                <!-- ログイン頁へ -->
                <li class = "nav-item">
                    <%= link_to login_path, class: "nav-link" do %>
                        <%= image_tag "icons/login.png", class: "hidden-xs" %><br>Login
                    <% end %>
                </li>
                <% end %>
            </ul>

        </nav>
        </div>

        <%= yield %>

        <script>
            $(function(){
              $(".alert").fadeOut(5000);
            });
        </script>

    </body>
    </html>

app/views/likes/index.html.erb
<div class="topic-index-wrapper">
   <div class="container">
   <!-- いいね一覧は写真のみ表示し、詳細は,show頁で　 -->
   <% @like_topics.each_with_index do |topic, i| %>
   <% if i % 3 == 0 %>
   <div class="row equal">
   <% end %>
              <div class="col-md-4 ">
                 <div class="topic-index-single">
                   <h2 class = "topic-author" style="align-items:start;">
                     <%= topic.user.name %>
                   </h2>
                   <div class="topic-image">
                     <% if topic.image.url.include?(".mp4") %>
                       <%= video_tag  topic.image.url,   :style => "width:100%;", controls: true, autobuffer: true %>
                    <% else %>
                       <%= image_tag topic.image.url %>
                     <% end %>
                   </div>
                   <h5 class = "topic-link">
                     <%= link_to("Fishing logへ", topic_path(id: topic.id) ) %>
                   </h5>
                 </div>
              </div>
  <% if i % 3 == 2 %>
  </div>
  <% end %>
  <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <!-- 投稿一覧は写真のみ表示し、詳細は,show頁で　 -->
    <% @topics.each_with_index do |topic, i| %>
    <% if i % 3 == 0 %>
    <div class="row equal">
    <% end %>
         <div class="col-md-4">
           <div class="topic-index-single h-100">
             <h2 class = "topic-author" style="align-items:start;">
               <%= topic.user.name %>
             </h2>
             <div class="topic-image" style="align-items:center;">
               <% if topic.image.url.include?(".mp4") %>
                 <%= video_tag  topic.image.url,   :style => "width:100%;", controls: true, autobuffer: true %>
              <% else %>
                 <%= image_tag topic.image.url %>
               <% end %>
             </div>
             <h5 class = "topic-link" style="align-items:end;">
               <%= link_to("Fishing logへ", topic_path(id: topic.id) ) %>
             </h5>
           </div>
         </div>
    <% if i % 3 == 2 %>
    </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row topic_new_form_size">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Fishing log</h1>
        <%= form_for @topic do |f| %>
           <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image %>
            </div>
            <div class="form-group">
              <%=  "日付" %>
              <%= f.date_select :f_date, {}, class: 'form_control' %>
            </div>
            <div class="form-group">
              <%= f.label :field, "エリア" %>
              <%= f.select :field, [["ミシガン", "ミシガン"], ["アマゾン","アマゾン"], ["ナイアガラ","ナイアガラ"]]  %>
            </div>
            <div class="form-group">
              <%= f.label :description, "釣り場メモ"  %><br>
              <%= f.text_area :description, class: 'form_control form_size' %>
            </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic-show-wrapper">
  <div class="container">

      <div class="row">
        <div class="col-md-8">
          <div class="show-index-single">

              <h2 class="topic-author">
                <%= @topic.user.name %>
              </h2>
              <div class="show-topic-image">
                <% if @topic.image.url.include?(".mp4") %>
                  <%= video_tag  @topic.image.url,   :style => "width:100%;", controls: true, autobuffer: true %>
                <% else %>
                  <%=image_tag @topic.image.url %>
                <% end %>
              </div>

              <div class="icon-area">
                <!-- いいねに登録済みならば、 -->
                <% if @topic.like_users.include?(current_user) %>
                   <%= link_to likes_path(topic_id: @topic.id),method: :delete, remote: true do %>
                     <%= image_tag "icons/red-heart.png",class: "topic-index-icon" %>
                   <% end %>
                   <!-- いいねの数を数える -->
                   <p class = "topic-text"><%= @topic.like_users.count %></p>
                <!-- いいねに未登録ならば、-->
                <% else %>
                   <%= link_to likes_path(topic_id: @topic.id),method: :post, remote: true do %>
                     <%= image_tag "icons/heart-black.png",class: "topic-index-icon" %>
                   <% end %>
                   <!-- いいねの数を数える -->
                   <p class="topic-text"><%= @topic.like_users.count %></p>
                <% end %>
                <!-- 投稿写真の削除機能 -->
                <% if @topic.user_id == current_user.id %>
                    <%= link_to topic_path(topic_id: @topic.id), method: :delete do %>
                       <%= image_tag "icons/delete.png", class: "topic-index-icon" %>
                    <% end %>
                <% end %>

              </div>
              <!--                （start)        詳細表示欄                                               -->
              <div class="topic-detail">
                <div class="topic-list">
                  <!-- 釣果日 表示欄-->
                  <h5 class="topic-f_date">
                    <hr>
                    <%= @topic.f_date %>
                  </h5>
                  <!-- フィールドエリア表示欄-->
                  <h5 class="topic-field">
                    <hr>
                    <%= "フィールドエリア： " + @topic.field %>
                  </h5>
                  <!-- 釣果メモ表示欄-->
                  <h5 class="topic-description">
                    <hr>
                    <%= @topic.description %>
                  </h5>
                </div>
              </div>

              <!--                （end) 詳細表示欄                                           -->
          </div>
        </div>

        <div class="col-md-4">
          <!-- コメント一覧　-->
          <div class="comments-index">
            <h4 class="topic-comment">◎◎◎コメント一覧◎◎◎</h4>
            <div class="comments-show">
              <% @topic.comments.each do |comment| %>
                  <span style="color:blue"><%= comment.user.name %> </span><%= comment.body %><br><span style="font-size: 12px;"><%= comment.created_at.strftime("%Y-%m-%d %H:%M")  %></span><br>
                  <!-- コメントの削除機能-->
                  <% if comment.user_id == current_user.id %>
                    <%= button_to "削除", { controller: "comments", :action => "destroy", :id => comment.id}, :method => 'delete' %>
                  <% end %>
              <% end %>
            </div>
            <!-- コメント投稿欄-->
            <div class="comment-input-group">
              <%= form_for(:comment, url: topics_comments_path) do |f| %>
                 <div class="comment-input">
                   <%= f.text_field :body, class: "form-control comment-input",style: "width:80%; height:30px; display: inline-block;" %>
                   <input type="image" src="/assets/icons/comment.png" class="topic-comment-icon">
                   <%= f.hidden_field :topic_id, :value => @topic.id %>
                 </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>

        <%= form_for @user do |f| %>
          <!-- 名前の入力フォーム -->
          <div class="form-group">
            <%= f.label :name, class: "text-white" %>
            <%= f.text_field :name, class: "form-control"%>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:name).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- メールアドレスの入力フォーム -->
          <div class="form-group">
            <%= f.label :email, class: "text-white"%>
            <%= f.text_field :email, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:email).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- パスワードの入力フォーム -->
          <div class="form-group">
            <%= f.label :password, class: "text-white"%>
            <%= f.text_field :password, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:password).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <!-- パスワードの確認フォーム -->
          <div class="form-group">
            <%= f.label :password_confirmation, class: "text-white"%>
            <%= f.text_field :password_confirmation, class: "form-control" %>
            <!-- エラーメッセージ -->
            <% if @user.errors.any? %>
              <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
                <p class="text-white"><%= message %></p>
              <% end %>
            <% end %>
          </div>
          <%= f.submit "登録", class: "btn-block btn-white"%>
        <% end %>
        <%= link_to "ログインはこちら",login_path,class: "text-white"%>
      </div>
    </div>
  </div>
</div>